[almalinux]
Webtactic_cpanel ansible_host=43.239.92.149 ansible_port=22017 ansible_user=root
Aroner-Cyberpanel ansible_host=43.239.92.112 ansible_port=22083 ansible_user=root
Maven-group ansible_host=103.98.6.149 ansible_port=22217 ansible_user=root
B2TECHSOFT ansible_host=103.25.126.204 ansible_port=22174 ansible_user=root
Diamond-Tools ansible_host=103.25.126.140 ansible_port=22135 ansible_user=root

[debian]
RestoMpos ansible_host=103.25.126.176 ansible_port=22864 ansible_user=root
VinayA ansible_host=43.239.92.114 ansible_port=22088 ansible_user=root
mongodb-server ansible_host=43.239.92.101 ansible_port=22243 ansible_user=root
ML-models ansible_host=43.239.92.102 ansible_port=22244 ansible_user=root
Python-compute ansible_host=43.239.92.103 ansible_port=22245 ansible_user=root
docker-exp_model ansible_host=43.239.92.107 ansible_port=22246 ansible_user=root
Phizica ansible_host=103.25.126.134 ansible_port=22118 ansible_user=root

[ubuntu]
Sakshi-Infotech ansible_host=142.79.228.254 ansible_port=22925 ansible_user=root
EPOC-APP-SCAN_Ardent__-_Linux ansible_host=142.79.228.252 ansible_port=22113 ansible_user=root
EPOC-AI-DATA_Ardent_-Linux ansible_host=142.79.228.253 ansible_port=22114 ansible_user=root
TreatyouEMR ansible_host=142.79.228.250 ansible_port=22915 ansible_user=root
Gitapress ansible_host=180.179.25.3 ansible_port=22102 ansible_user=root
Gitapress-dev ansible_host=180.179.25.4 ansible_port=22103 ansible_user=root
HRMSINDIA-_AHK_ ansible_host=103.98.6.181 ansible_port=22885 ansible_user=root
busisoft-linux ansible_host=103.25.126.119 ansible_port=22094 ansible_user=root
Valensc_Solutions ansible_host=103.25.126.133 ansible_port=22116 ansible_user=root
SMN ansible_host=103.25.126.93 ansible_port=22162 ansible_user=root
ActureMedia ansible_host=43.239.92.177 ansible_port=22253 ansible_user=root
Lewituz-OdooPOS01 ansible_host=43.239.92.173 ansible_port=22242 ansible_user=root
HCP-DB ansible_host=43.239.92.119 ansible_port=22098 ansible_user=root
Forexai ansible_host=43.239.92.162 ansible_port=22086 ansible_user=root
agram_cloud ansible_host=103.25.126.239 ansible_port=22216 ansible_user=root
ARDENT-CM ansible_host=43.239.92.145 ansible_port=22829 ansible_user=root
ARDENT-Gateway ansible_host=43.239.92.133 ansible_port=22030 ansible_user=root
ARDENT-PA ansible_host=43.239.92.35 ansible_port=22031 ansible_user=root
gyri-products ansible_host=103.25.126.72 ansible_port=22111 ansible_user=root
Master-pathology ansible_host=43.239.92.124 ansible_port=22542 ansible_user=root
WSC_VM22_POS ansible_host=142.79.228.58 ansible_port=22038 ansible_user=root
HCP ansible_host=43.239.92.119 ansible_port=22097 ansible_user=root
ASCENSIA ansible_host=43.239.92.120 ansible_port=22098 ansible_user=root
NEXTCLOUD-SQUER ansible_host=43.239.92.121 ansible_port=22099 ansible_user=root
PhoenixSoftnet-CPANEL ansible_host=43.239.92.176 ansible_port=22040 ansible_user=root
Vlite ansible_host=43.239.92.55 ansible_port=22184 ansible_user=root
KLCMS ansible_host=103.25.126.219 ansible_port=22147 ansible_user=root
KLWEB ansible_host=103.25.126.220 ansible_port=22148 ansible_user=root
KLDB ansible_host=103.25.126.221 ansible_port=22149 ansible_user=root
asc-enc-001 ansible_host=103.25.126.222 ansible_port=22150 ansible_user=root
Triton ansible_host=103.25.126.217 ansible_port=22144 ansible_user=root
Lewituz-A012 ansible_host=103.98.6.85 ansible_port=22128 ansible_user=root
Yaxa ansible_host=103.25.126.112 ansible_port=22229 ansible_user=root
Saavi-showroom_OrnateCRM_ ansible_host=103.25.126.202 ansible_port=22169 ansible_user=root
Maven-group ansible_host=103.25.126.196 ansible_port=22156 ansible_user=root
Capsicum_-_cPanel ansible_host=103.98.6.116 ansible_port=22225 ansible_user=root
Inovant-app ansible_host=103.98.6.225 ansible_port=22113 ansible_user=root
Inovant-db ansible_host=103.98.6.226 ansible_port=22114 ansible_user=root
Adbis-app ansible_host=103.98.6.249 ansible_port=22167 ansible_user=root
Adbis-db ansible_host=103.98.6.250 ansible_port=22168 ansible_user=root
Transtrade ansible_host=103.25.126.126 ansible_port=22073 ansible_user=root
Novus_Logic ansible_host=103.25.126.167 ansible_port=22105 ansible_user=root
RestroBomb ansible_host=103.25.126.114 ansible_port=22054 ansible_user=root
BENCHMARK ansible_host=103.170.114.109 ansible_port=22109 ansible_user=root
OrnateCRM ansible_host=103.25.126.164 ansible_port=22164 ansible_user=root
Golden_Hospitality ansible_host=103.98.6.143 ansible_port=22203 ansible_user=root
Grinntech ansible_host=123.108.43.251 ansible_port=22127 ansible_user=root
Ebtechlinux ansible_host=103.170.114.168 ansible_port=22191 ansible_user=root
MTK ansible_host=103.170.114.17 ansible_port=22227 ansible_user=root
Legacy-Square ansible_host=103.25.126.139 ansible_port=22132 ansible_user=root
SUNSHINE ansible_host=103.25.126.141 ansible_port=22136 ansible_user=root
Squer-Ticketing ansible_host=43.239.92.123 ansible_port=22941 ansible_user=root
Kalpsutra ansible_host=103.25.126.150 ansible_port=22151 ansible_user=root
Nu-pie ansible_host=103.25.126.152 ansible_port=22159  ansible_user=root
SVSM ansible_host=103.25.126.154 ansible_port=22163 ansible_user=root

[fedora]
SAK-MUM ansible_host=103.25.126.1 ansible_port=22714 ansible_user=root
SachMUM ansible_host=43.239.92.143 ansible_port=22023 ansible_user=root
KTMUM ansible_host=43.239.92.131 ansible_port=22956 ansible_user=root

[linux]
Unicrmbiz__unistrat_ ansible_host=43.239.92.108 ansible_port=22253 ansible_user=root
Quantum-IT-Linux ansible_host=123.108.59.100 ansible_port=22200 ansible_user=root
GEPL-HANA ansible_host=103.98.6.104 ansible_port=22152 ansible_user=root

[all:vars]
ansible_connection=ssh
#ansible_ssh_private_key_file=/var/lib/rundeck/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
